package com.rcorp.airpokecross.config

object ConfigSpriteKey {
    val LOGIN_SCREEN_BACKGROUND = "LOGIN_SCREEN_BACKGROUND"
    val SELECT_CHARACTER_BACKGROUND = "SELECT_CHARACTER_BACKGROUND"
    val CREATE_CHARACTER_FRAME = "CREATE_CHARACTER_FRAME"
}